version: "2.0"
services:
  vk2discord-docker:
    container_name: vk2discord-docker
    image: mrzillagold/vk2discord:latest
    volumes:
      - /opt/vk2discord/config.json:/usr/src/vk2discord/config.json
      - /opt/vk2discord/cache.json:/usr/src/vk2discord/cache.json
      - /opt/vk2discord/news.json:/usr/src/vk2discord/news.json
    restart: always
    tmpfs:
      - /tmp
